<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>CrossReview</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CrossReview.Application\CrossReview.Application.csproj" />
      <ProjectReference Include="..\Crossreview.Infrastructure.Identity\Crossreview.Infrastructure.Identity.csproj" />
      <ProjectReference Include="..\CrossReview.Infrastructure.Postgres\CrossReview.Infrastructure.Postgres.csproj" />
    </ItemGroup>

</Project>
